FROM morapresence/mond_db_debug:latest

WORKDIR /app

COPY ClientDB ./ClientDB
COPY CMake ./CMake
COPY ConnectionHandler ./ConnectionHandler
COPY DBCore ./DBCore
COPY Initializer ./Initializer
COPY scripts ./scripts
COPY InternalEntities ./InternalEntities
COPY ServerDB ./ServerDB
COPY Tests ./Tests
COPY ./CMakeLists.txt ./
COPY ./.clang-format ./