name: CI

on:
  push:
    branches: ["main", "dev/ci_setup", "dev/MoraPresence", "dev/Nikitylllka", "dev/ogrebatel", "dev/darioshka"]
  pull_request:
    branches: ["main", "dev/ci_setup", "dev/MoraPresence", "dev/Nikitylllka", "dev/ogrebatel", "dev/darioshka"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:


  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container: morapresence/mond_db_tests

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: | 
          cmake --build ${{github.workspace}}/build
          ls -la ${{github.workspace}}/build
          ls -la ${{github.workspace}}/build/Tests/

      - name: Test
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: .${{github.workspace}}/build/Tests/MOND_DB_TESTS
  tests:
    needs: [build]

    runs-on: ubuntu-latest
    container: morapresence/mond_db_tests

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: .${{github.workspace}}/build/Tests/MOND_DB_TESTS


  linters:
    needs: [ build ]

    runs-on: ubuntu-latest
    container: morapresence/mond_db_tests

    steps:
      - uses: actions/checkout@v3
      - name: run_linters
        working-directory: ${{github.workspace}}
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: |
          chmod 777 ./linters/linters.sh
          ./linters/linters.sh

  sanitisers:
    needs: [build]

    runs-on: ubuntu-latest
    container: morapresence/mond_db_tests

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: valgrind
        run: valgrind --tool=memcheck --leak-check=yes ${{github.workspace}}/build/Tests/MOND_DB_TESTS