name: CI

on:
  push:
    branches: [ "main", "workflow_setup", "dev/ci_setup", "dev/MoraPresence", "dev/Nikitylllka", "dev/ogrebatel", "dev/darioshka" ]
  pull_request:
    branches: [ "main", "workflow_setup", "dev/ci_setup", "dev/MoraPresence", "dev/Nikitylllka", "dev/ogrebatel", "dev/darioshka" ]

env:
  BUILD_TYPE: Debug

jobs:


  build-project:
    runs-on: ubuntu-latest
    container: morapresence/mond_db_tests

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{ github.workflow }}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{ github.workflow }}/build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workflow }}/build/**/*

  tests:
    needs: [ build-project ]

    runs-on: ubuntu-latest
    container: morapresence/mond_db_tests

    steps:
      - uses: actions/checkout@v3

      #      - name: Configure CMake
      #        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}#
      #
      #      - name: Build
      #        run: cmake --build ${{github.workspace}}/build

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workflow }}/build

      - name: Move to workspace
        run: |
          mkdir -p ${{ github.workspace }}/build
          mv ${{ github.workflow }}/build/* ${{ github.workspace }}/build

      - name: Test
        run: |
          cd ${{ github.workspace }}/build/Tests/
          chmod 777 MOND_DB_TESTS
          ./MOND_DB_TESTS


  linters:
    needs: [ build-project ]

    runs-on: ubuntu-latest
    container: morapresence/mond_db_tests

    steps:
      - uses: actions/checkout@v3
      - name: run_linters
        working-directory: ${{github.workspace}}
        run: |
          chmod 777 ./linters/linters.sh
          ./linters/linters.sh

  sanitisers:
    needs: [ build-project ]

    runs-on: ubuntu-latest
    container: morapresence/mond_db_tests

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workflow }}/build

      - name: Move to workspace
        run: |
          mkdir -p ${{ github.workspace }}/build
          mv ${{ github.workflow }}/build/* ${{ github.workspace }}/build

      - name: valgrind
        run: |
          chmod 777 ${{github.workspace}}/build/Tests/MOND_DB_TESTS
          valgrind --tool=memcheck --leak-check=yes ${{github.workspace}}/build/Tests/MOND_DB_TESTS