name: Tests

on:
  push:
    branches: [ "main", 'dev/**' ]

env:
  BUILD_TYPE: Release

jobs:
  linters:
    runs-on: ubuntu-latest
    container: morapresence/mond_db_debug

    steps:
      - uses: actions/checkout@v3
      - name: run_linters
        run: bash scripts/linters/linters.sh

  build-project:
    runs-on: ubuntu-latest
    container: morapresence/mond_db_debug

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ${{ github.workspace }}/build/**/*

  tests:
    needs: [ build-project ]

    runs-on: ubuntu-latest
    container: morapresence/mond_db_debug

    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ${{ github.workspace }}/build

      - name: Move to workspace
        run: |
          mkdir -p ${{ github.workspace }}/build
          mv ${{ github.workspace }}/build/* ${{ github.workspace }}/build

      - name: Test
        run: |
          cd ${{ github.workspace }}/build/Tests/
          chmod 777 MOND_DB_TESTS
          ./MOND_DB_TESTS

      - name: Coverage
        run: |
          cd ${{ github.workspace }}/build/Tests/
          chmod 777 MOND_DB_TESTS
          ./MOND_DB_TESTS
          ls -la ${{ github.workspace }}
          cd ${{ github.workspace }}/build/Tests/CMakeFiles/MOND_DB_TESTS.dir
          gcov tests.cpp.o
          lcov -t . -o coverage_report.info -c -d .
          genhtml -o coverage_report coverage_report.info

      - name: Upload tests artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tests-artifact
          path: ${{ github.workspace }}/build/**/*

  valgrind:
    needs: [ build-project ]

    runs-on: ubuntu-latest
    container: morapresence/mond_db_debug

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ${{ github.workspace }}/build

      - name: Move to workspace
        run: |
          mkdir -p ${{ github.workspace }}/build
          mv ${{ github.workspace }}/build/* ${{ github.workspace }}/build

      - name: valgrind
        run: |
          chmod 777 ${{github.workspace}}/build/Tests/MOND_DB_TESTS
          valgrind --tool=memcheck --leak-check=yes ${{github.workspace}}/build/Tests/MOND_DB_TESTS
